export const CREATE_NEW_CATEGORY = 'CREATE_NEW_CATEGORT';
export const UPDATECATEGORY = 'UPDATECATEGORT';
export const DELETECATEGORY = 'DELETECATEGORT';
export const FETCH_ALL_CATEGORIES= 'FETCH_ALL_CATEGORIES';
